server:
  port: 8080

logging:
  level:
    root: WARN
    com.mi4alsky.magicscrollshop: DEBUG
    org.springframework.orm.jpa: DEBUG

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show_sql: true
        format_sql: true
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/magic_store?
    username: postgres
    password: postgres
liquibase:
  change-log: classpath:liquibase/master-changelog.yml